"""
Report generation module for Utayomi
Generates reproducibility reports for selection.py output
"""
import sys
import os
import subprocess
import datetime
from typing import Dict, Any, Optional


def get_git_info() -> Dict[str, str]:
    """Get git repository information"""
    try:
        # Get repository URL
        repo_url = subprocess.check_output(
            ['git', 'remote', 'get-url', 'origin'], 
            cwd=os.path.dirname(os.path.dirname(__file__)),
            universal_newlines=True
        ).strip()
        
        # Get current commit hash
        commit_hash = subprocess.check_output(
            ['git', 'rev-parse', 'HEAD'],
            cwd=os.path.dirname(os.path.dirname(__file__)),
            universal_newlines=True
        ).strip()
        
        # Get current branch
        branch = subprocess.check_output(
            ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
            cwd=os.path.dirname(os.path.dirname(__file__)),
            universal_newlines=True
        ).strip()
        
        return {
            'repository_url': repo_url,
            'commit_hash': commit_hash,
            'branch': branch
        }
    except subprocess.CalledProcessError:
        return {
            'repository_url': 'Unknown (not a git repository)',
            'commit_hash': 'Unknown',
            'branch': 'Unknown'
        }


def get_command_info() -> Dict[str, str]:
    """Get information about the executed command"""
    command_line = ' '.join(sys.argv)
    python_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    
    return {
        'command_line': command_line,
        'python_version': python_version,
        'execution_time': datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }


def generate_reproducibility_report(
    version: str,
    model_identifier: str,
    config_file: str,
    application: Optional[str] = None,
    theme: Optional[str] = None,
    num_selections: Optional[int] = None,
    is_series: bool = False,
    is_tts: bool = False,
    is_debug: bool = False
) -> str:
    """Generate a comprehensive reproducibility report"""
    
    git_info = get_git_info()
    command_info = get_command_info()
    
    report_lines = [
        "",
        "---",
        "",
        "## 再現性レポート",
        "",
        "このファイルは以下の環境・設定で生成されました。",
        "",
        "### システム情報",
        f"- **Utayomi バージョン**: {version.strip()}",
        f"- **Python バージョン**: {command_info['python_version']}",
        f"- **実行日時**: {command_info['execution_time']}",
        "",
        "### リポジトリ情報",
        f"- **リポジトリURL**: {git_info['repository_url']}",
        f"- **ブランチ**: {git_info['branch']}",
        f"- **コミットハッシュ**: {git_info['commit_hash'][:8]}",
        "",
        "### 実行設定",
        f"- **使用モデル**: {model_identifier}",
        f"- **設定ファイル**: {config_file}",
    ]
    
    if application:
        report_lines.append(f"- **応募企画**: {application}")
    
    if theme and theme != "0":
        report_lines.append(f"- **お題**: {theme}")
    
    if num_selections:
        report_lines.append(f"- **選択数**: {num_selections}")
    
    # オプション設定
    options = []
    if is_series:
        options.append("連作モード")
    if is_tts:
        options.append("TTS生成")
    if is_debug:
        options.append("デバッグモード")
    
    if options:
        report_lines.extend([
            f"- **オプション**: {', '.join(options)}",
        ])
    
    report_lines.extend([
        "",
        "### 実行コマンド",
        "```bash",
        command_info['command_line'],
        "```",
        "",
        "### 再現方法",
        "1. 上記リポジトリの指定コミットをチェックアウト",
        "2. 必要な依存関係をインストール: `pip install -r requirements.txt`",
        "3. APIキーを設定: `.env`ファイルに必要なAPIキーを記述",
        "4. 上記実行コマンドを実行",
        "",
        f"*Generated by Utayomi Report Generator - {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        ""
    ])
    
    return '\n'.join(report_lines)


def append_report_to_markdown(markdown_path: str, report: str) -> None:
    """Append reproducibility report to existing markdown file"""
    try:
        with open(markdown_path, 'a', encoding='utf-8') as f:
            f.write(report)
    except Exception as e:
        print(f"Warning: Could not append report to {markdown_path}: {e}")


def remove_reproducibility_report(markdown_content: str) -> str:
    """Remove reproducibility report section from markdown content for TTS processing"""
    # 再現性レポートセクションの開始位置を検索
    report_start_patterns = [
        "\n---\n\n## 再現性レポート",  # 標準的なパターン
        "\n## 再現性レポート",         # --- なしのパターン  
        "---\n\n## 再現性レポート",     # 先頭の場合
        "## 再現性レポート"            # 最も単純なパターン
    ]
    
    for pattern in report_start_patterns:
        if pattern in markdown_content:
            # パターンが見つかった場合、そこから末尾までを除去
            report_start_index = markdown_content.find(pattern)
            cleaned_content = markdown_content[:report_start_index].rstrip()
            return cleaned_content
    
    # 再現性レポートが見つからない場合は元のコンテンツをそのまま返す
    return markdown_content